// <auto-generated />
namespace Maybank.InfrastructurePersistent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201907091830 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201907091830));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091029490_201907091830"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
